---
title: "Introduction to Data Science with R"
subtitle: "posit::conf(2023)"
format: 
  html:
    toc: true
---

## Welcome

This is not a standard workshop, but a six-week online apprenticeship that culminates in two in-person days at posit::conf(2023). Here, you will learn the foundations of R and the Tidyverse under the guidance of a Posit Academy mentor and in the company of a close group of fellow learners. 

You will be expected to complete a weekly curriculum of interactive tutorials, and to attend a weekly presentation meeting with your mentor and fellow students. Topics will include the basics of R, importing data, visualizing data with ggplot2, wrangling data with dplyr and tidyr, working with strings, factors, and date-times, and reporting reproducibly with Quarto. Begins August 7th, 2023. No knowledge of R required. 

Visit [posit.co/academy](https://posit.co/products/enterprise/academy/) to learn more about this uniquely effective learning format.

**This course is ideal for:**

* those new to R or the Tidyverse

* anyone who has dabbled in R, but now wants a rigorous foundation in up-to-date data science best practices

* SAS and Excel users looking to switch their workflows to R

## Schedule & Materials

### Day 1

| Time          | Activity                              | Slides
| :------------ | :------------------------------------ | :----- |
| 09:00 - 09:30 | Session 0 - Welcome                   | [Slides](https://intro-tidyverse-2023.netlify.app/_slides/session01-welcome-slides.html){target="_blank" rel="noopener noreferrer"}
| 09:30 - 10:30 | Session 1 - Review & Practice         | [Slides](https://intro-tidyverse-2023.netlify.app/_slides/session01-practice-slides.html){target="_blank" rel="noopener noreferrer"}|
| 10:30 - 11:00 | *Coffee break*                        |  |
| 11:00 - 12:30 | Session 2 - Exploratory Data Analysis | [Slides](https://github.com/posit-conf-2023/r-intro/blob/main/slides/session02-eda.pdf){target="_blank" rel="noopener noreferrer"} |
| 12:30 - 13:30 | *Lunch break*                         |  |
| 13:30 - 15:00 | Session 3 - Intro to Quarto           | [Slides](https://intro-tidyverse-2023.netlify.app/_slides/session03-quarto-slides.html){target="_blank" rel="noopener noreferrer"} |
| 15:00 - 15:30 | *Coffee break*                        |  |
| 15:30 - 17:00 | Session 4 - Build & publish reports   | [Slides](https://github.com/posit-conf-2023/r-intro/blob/main/slides/session04-reports.pdf){target="_blank" rel="noopener noreferrer"}  |

### Day 2

| Time          | Activity                             | Slides
| :------------ | :----------------------------------- | :----- |
| 09:00 - 10:30 | Session 5 - Best practices           | [Slides](https://github.com/posit-conf-2023/r-intro/blob/main/slides/session05-best-practices.pdf){target="_blank" rel="noopener noreferrer"} |
| 10:30 - 11:00 | *Coffee break*                       |  |
| 11:00 - 12:30 | Session 6 - Explore a new data set   | [Slides](https://github.com/posit-conf-2023/r-intro/blob/main/slides/session06-new-data.pdf){target="_blank" rel="noopener noreferrer"} |
| 12:30 - 13:30 | *Lunch break*                        |  |
| 13:30 - 15:00 | Session 7 - Data types               | [Slides](https://intro-tidyverse-2023.netlify.app/_slides/session07-types-slides.html){target="_blank" rel="noopener noreferrer"} |
| 15:00 - 15:30 | *Coffee break*                       |  |
| 15:30 - 17:00 | Session 8 - Share projects & Wrap-up |  |
